version: 0.0
os: windows
files:
  - source: Settings
    destination: C:\Program Files\Amazon\Ec2ConfigService\Settings
hooks:
  BeforeInstall:
    - location: remove_previous_configs.bat
      timeout: 30
  ApplicationStart:
    - location: restart_service.bat
      timeout: 60

